### ISSUE TITLE
Syntax Warning on first run of `trye`

### ISSUE THREAD

**Issue by my1e5** [Zaloog/rye-tui#1]
Installed via `rye install rye-tui`

On first run of `trye` I got this Syntax Warning.
```
❯ trye
/Users/my1e5/.rye/tools/rye-tui/lib/python3.12/site-packages/rye_tui/components/modals.py:122: SyntaxWarning: invalid escape sequence '\.'
  validators=[Regex("^3\.(?:[89]|1[012])$")],
[21:33:31] Thank you for using "rye-tui".
           Since this is your first time using "rye-tui" a Configuration-File
           was created successfully.
           You can now use "trye" again to start working with rye-tui.
```

**Comment by Zaloog** [comment]
Hi @my1e5 ,

I think I that has to do with the  Regex String not being a raw string.
Let me push a fix really quick

**Comment by Zaloog** [comment]
@my1e5 
can you update your version to `v0.2.2`.
I just published the fix

**Comment by my1e5** [comment]
I did `rye uninstall rye-tui` and then `rye install rye-tui` 
```
❯ trye --version
rye-tui 0.2.2
```
But it must still detect the configuration file from before. Where is that located? I should try delete that and then running `trye` should allow me to test your fix.

**Comment by my1e5** [comment]
Found the `rye-tui` folder in `/Library/Application Support` and deleted the folder.
```
❯ trye
[22:11:01] Thank you for using "rye-tui".
           Since this is your first time using "rye-tui" a Configuration-File was created successfully.
           You can now use "trye" again to start working with rye-tui.
```
All working
